### ISSUE TITLE
Automated server sync removes attribute sync_safe

### ISSUE THREAD

**Issue by frankystone** [widelands/wl_addons_server#120]
Is it intendet that the minimalistic theme is suddenly not sync_safe anymore?
See:
https://github.com/widelands/wl_addons_server/commit/aca22a8db6009966d9dd02a0723f0ba914c4ee2a#diff-f94dc0d90ace9bbf3f662bc4809644a461e3f0e77f4eb16db62704e7c5b2f582

**Comment by Noordfrees** [comment]
That's because you created the latest upgrade with your local copy of the add-on instead of a fresh copy from the server, and your local copy didn't contain the remote changes. The sync_safe key needs to be written into the add-on itself rather than storing it as metadata to ensure it's always available offline. I forgot to re-add the flag when verifying the add-on – did so now.

**Comment by frankystone** [comment]
Thanks :-)
